import { z } from 'zod'

export const EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_PUSH = 'GithubNewPush'
export const EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_WORKFLOW_RUN_EVENT = 'GithubNewWorkflowRunEvent'
export const EVENTBRIDGE_DETAIL_TYPE_WEB_PUSH_TEST = 'WebPushTest'
export const EVENTBRIDGE_DETAIL_TYPE_INSTALLATION_UPDATED = 'InstallationUpdated'
export const EVENTBRIDGE_DETAIL_TYPE_PUBLIC_ACCOUNT_UPDATED = 'PublicAccountUpdated'
export const EVENTBRIDGE_DETAIL_TYPE_GITHUB_REPO_ACTIVITY_TABLE_UPDATED = 'GithubRepoActivityTableUpdated'

export const EVENT_BRIDGE_DETAIL_TYPES = [
  EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_PUSH,
  EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_WORKFLOW_RUN_EVENT,
  EVENTBRIDGE_DETAIL_TYPE_WEB_PUSH_TEST,
  EVENTBRIDGE_DETAIL_TYPE_INSTALLATION_UPDATED,
  EVENTBRIDGE_DETAIL_TYPE_PUBLIC_ACCOUNT_UPDATED,
  EVENTBRIDGE_DETAIL_TYPE_GITHUB_REPO_ACTIVITY_TABLE_UPDATED
] as const

export const WEBPUSH_EVENTBRIDGE_DETAIL_TYPES = [
  EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_PUSH,
  EVENTBRIDGE_DETAIL_TYPE_GITHUB_NEW_WORKFLOW_RUN_EVENT,
  EVENTBRIDGE_DETAIL_TYPE_WEB_PUSH_TEST
] as const

export const EventBridgeDetailTypeSchema = z.literal(EVENT_BRIDGE_DETAIL_TYPES)
export const WebpushEventBridgeDetailTypeSchema = z.literal(WEBPUSH_EVENTBRIDGE_DETAIL_TYPES)

export type EventBridgeDetailType = z.infer<typeof EventBridgeDetailTypeSchema>
export type WebPushEventBridgeDetailType = z.infer<typeof WebpushEventBridgeDetailTypeSchema>
